# Generated by Django 4.0.5 on 2023-08-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_vehiculo_condicion_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='precio',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
